name: Configuring ci/cd

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:

  ci:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        env: 
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker build -t logaka/repo .
      - name: Push Docker Image
        run: docker push logaka/repo:latest
        if: always()
        
  cd:
    needs: 
      - ci
    runs-on: ec2

    steps:
      - name: Pull Docker Image
        run: docker pull $DOCKER_USERNAME/repo:latest
      - name: Delete old repo
        run: docker rm -f repo-container || true
      - name: Run Docker Image
        run: dokcer run -d -p 80:8080 --name repo-container $DOCKER_USERNAME/repo:latest




    
    
